### ISSUE TITLE
Feature: allow `data.frame` or named vector to be passed into `create_item()`

### ISSUE THREAD

**Issue by leungi** [Azure/Microsoft365R#10]
Was looking for a `create_item()` method for current project, and serendipitously saw your implementation in latest commit 👏 🙏 

With reference to the `create_item()` method, we're trying to pass in a `data.frame`/named vector object with a trick (see below) that was expected to work, but failed.
https://github.com/Azure/Microsoft365R/blob/3b61905781e88c972fb93564757c05510649e274/R/ms_list.R#L90

#### Regular function call that works
```r
# Title and Value are available SharePoint List columns
lst$create_item(Title = "demo", Value = "1")
```
#### Trick to pass in `data.frame` that should work, but failed
1. Re-define `list()` method to overwrite base one
```r
list <- function(...){
  as.list(...)
}
```

2. Create named vector out from `data.frame` to pass into `create_item()`
```r
my_data <- data.frame(Title = "demo", Value = "1", stringsAsFactors = FALSE)

(setNames(
    c(unlist(my_data)),
    names(my_data)
))
#>  Title  Value 
#> "demo"    "1" 
```

3. Pass into `create_item()`
```r
lst$create_item(
  setNames(
    c(unlist(my_data)),
    names(my_data)
  )
)

#> Error in process_response(res, match.arg(http_status_handler), simplify) : 
#>   Bad Request (HTTP 400). Failed to complete operation. Message:
#> Property fields in payload has a value that does not match schema.
```

**Comment by hongooi73** [comment]
The underlying create-item API call is rather crippled; it only adds one item at a time. If you want to add multiple items, this hack should work:

```r
lapply(1:nrow(df), function(i) do.call(lst$create_item, df[i, ]))
```

**Comment by leungi** [comment]
A guru you are 🙇‍♂️

Since it's underlying constraint, I suspect the effort to fix at source will be big; closing it as hack is 👌

**Comment by hongooi73** [comment]
It's still a useful convenience function to have. I'll put it on the to-do list.

**Comment by leungi** [comment]
@hongooi73 , I had the same thought (e.g., `create_items()`), but didn't want to put the onus on you.

Please let me know if I can help; if it's within my technical capability, I'll sign up.

**Comment by hongooi73** [comment]
It won't be that fancy, lol. I've just added a `bulk_import` one-line method that calls `create_item` as shown above.
