### ISSUE TITLE
Cannot upload a file

### ISSUE THREAD

**Issue by ilona-grabowicz** [Azure/Microsoft365R#100]
I have a following issue. 

This is my code: 
```
library(Microsoft365R)

odb <- get_business_onedrive()

my_file <- 'report.xlsx'

files <- odb$list_items('ContentGap_reports')

print(files)

odb$upload_file(src = my_file, dest = paste0('/ContentGap_reports/',my_file))
```

It works all fine when I run it manually. However when I run the code in cron I get the following error:
```
Error in private$get_root()$upload(src, dest, blocksize) : 
  Unauthorized (HTTP 401).
Calls: <Anonymous> -> <Anonymous> -> <Anonymous>
Execution halted
```
Even printing the files works fine, it just is not authorised to upload. Any solutions???

**Comment by hongooi73** [comment]
I'm not familiar with how cron handles user accounts. Is it using your own account? If so, there shouldn't be any difference between running it via cron and doing it manually.
