### ISSUE TITLE
Incorrect drive returned from get_drive with drive_name parameter

### ISSUE THREAD

**Issue by vladvaculin** [Azure/Microsoft365R#104]
The drive returned from any `get_drive` function, by using the `drive_name` parameter, is incorrect. It returns the first drive on the list instead of the found one. For example, in [add_methods.R](https://github.com/Azure/Microsoft365R/blob/master/R/add_methods.R):
https://github.com/Azure/Microsoft365R/blob/6f43ccc9e7de31974286ff45533354b60b803264/R/add_methods.R#L234-L253
The return is `drives[[1]]` when only the `drive_name` is param is set and it actually matches one of the drives from the list of drives (and it's unique).

Similar, the same issue is in:
[ms_site.R](https://github.com/Azure/Microsoft365R/blob/6f43ccc9e7de31974286ff45533354b60b803264/R/ms_site.R#L74):
https://github.com/Azure/Microsoft365R/blob/6f43ccc9e7de31974286ff45533354b60b803264/R/ms_site.R#L74
and

[ms_team.R](https://github.com/Azure/Microsoft365R/blob/6f43ccc9e7de31974286ff45533354b60b803264/R/ms_team.R#L128):
https://github.com/Azure/Microsoft365R/blob/6f43ccc9e7de31974286ff45533354b60b803264/R/ms_team.R#L128

### To replicate/test
Try to get two different existent drives from a site/team/group by using `get_drive(drive_name=)`. Without any changes, the result would be the default drive, whilst the expected result is two different drives.

### Possible solution
Changing the return line from `drives[[1]]` to `drives[[wch]]`, since `wch` already contains the correct index at which the desired drive exists. So the mentioned functions would be:
```
function(drive_name=NULL, drive_id=NULL)
    {
        if(!is.null(drive_name) && !is.null(drive_id))
            stop("Supply at most one of drive name or ID", call.=FALSE)
        if(!is.null(drive_name))
        {
            # filtering not yet supported for drives, do it in R
            drives <- self$list_drives()
            wch <- which(sapply(drives, function(drv) drv$properties$name == drive_name))
            if(length(wch) != 1)
                stop("Invalid drive name", call.=FALSE)
            return(drives[[wch]])
        }
    # continuation
```

### Additional comments
I think it would be beneficial if there were some tests that would catch this kind of scenario in the future.

**Comment by hongooi73** [comment]
I've pushed a fix to the Master branch. Can you try it and let me know if it works?

**Comment by vladvaculin** [comment]
It works. Many thanks!
