### ISSUE TITLE
read csv files into a data frame

### ISSUE THREAD

**Issue by danielruss** [Azure/Microsoft365R#105]
Hi,
   Can how add functionality to read csv/tsv files directly into memory?  Similar to how boxr does it.
Daniel

**Comment by hongooi73** [comment]
Use the `save_dataframe` and `load_dataframe` methods to transfer data frames to/from csv/tsv files. See `?ms_drive` and `?ms_drive_item` for more info.

**Comment by danielruss** [comment]
Thank you @hongooi73.   Works great for csv/tsv.  It would be even better if you allow me to pass a callback function to allow reading of other file types.  Thank you again.
