### ISSUE TITLE
Issue when using Download_File function

### ISSUE THREAD

**Issue by matman89** [Azure/Microsoft365R#11]
Hello,

I am able to authenticate and open an item using drive$open_item but am getting a error when attempting to run the code: ```drv$download_file(path, dest = "Data/Test.xlsx", overwrite = TRUE)```,

This is the error message:
``` Error in curl::curl_fetch_disk(url, x$path, handle = handle) : TCP connection reset by peer ```

The system is running Centos 8, R version 3.5.1

**Comment by hongooi73** [comment]
That looks like a network error, not anything related to the package or R generally. Try it again after waiting for a bit.
