### ISSUE TITLE
Unable to upload file on one drive business

### ISSUE THREAD

**Issue by da2807** [Azure/Microsoft365R#114]
Hi, 

Have been exploring the MicrosoftR package to _upload files_ to Microsoft one drive business but with no luck! 

Am using `odb$upload_file` function following documentation here [(https://github.com/Azure/Microsoft365R)]. The only difference is that the one drive functions are explained for one drive personal and not business. 
E.g.  when i run below, receive the following error: 
`odb$upload_file("filename2022.csv")`

> Error in private$make_absolute_path(dest) : 
>   argument "dest" is missing, with no default

What should be the destination path here? have tried several combinations of the one drive link, however none work. 

Thanks
AD

**Comment by hongooi73** [comment]
The Onedrive interface functions identically for the personal and business versions. As the documentation in `?ms_drive` states:

> `download_file` and `upload_file` transfer files between the local machine and the drive. For `download_file`, the default destination folder is the current (working) directory of your R session. **For `upload_file`, there is no default destination folder; make sure you specify the destination explicitly.**

The destination should be the name of the file when uploaded, along with an optional directory, like this:

```r
odb$upload_file("filename2022.csv", "filename2022.csv")

# renaming on upload
odb$upload_file("filename2022.csv", "filename_new.csv")

# uploading to a directory
odb$upload_file("filename2022.csv", "path/to/dir/filename2022.csv")
```
