### ISSUE TITLE
get_subsite() not available

### ISSUE THREAD

**Issue by berlioz5** [Azure/Microsoft365R#115]
Hi - i am trying to access a subsite inside a  SharePoint library. after review, I found the below snippet from the OneDrive and SharePoint vignette. however, when I try to use get_subsite() it doesn't seem to be a valid method. does anyone have experience accessing subsites or can someone point me to what i'm doing wrong? i've had no probem accessing sharepoint root sites and drives. just seem to be having this issue with subsites. 

vignettes/od_sp.Rmd 

> Finally, you can retrieve subsites with `list_subsites()` and `get_subsite()`. These also return SharePoint site objects, so all the methods above are available for a subsite.

**Comment by hongooi73** [comment]
Can you provide a sample of the failing code? What error are you getting?

**Comment by hongooi73** [comment]
Looks like for whatever reason, I forgot to implement `get_subsite`. However, you don't actually need it; you can just use the result of `list_subsites`. That's just a list of objects representing all the subsites of your site.

```
sp_site$list_subsites()[[1]]  # 1st subsite
sp_site$list_subsites()[[2]]  # 2nd subsite
```

**Comment by hongooi73** [comment]
And yes, I'm available for consulting! You can email me at the package maintainer address: hongooi73 (at) gmail.com.

**Comment by hongooi73** [comment]
Actually, the reason I didn't implement `get_subsite` is because there's no documented API call for this. Instead, try using the regular `get_sharepoint_site` function, and pass it the URL for your subsite.

Disclaimer: I don't have access to a business MS365 sub right now, so I can't test this.

**Comment by berlioz5** [comment]
thank you! that worked. I might reach out in the next few weeks. I appreciate your help.
