### ISSUE TITLE
delete_item won't accept confirm = TRUE argument

### ISSUE THREAD

**Issue by mpr1255** [Azure/Microsoft365R#117]
Hello, 

Run this code to duplicate the bug: 

```
system("echo 'hello world' > ./testfile.txt")
od$upload_file("./testfile.txt", "testfile.txt")
od$delete_item("testfile.txt", confirm = TRUE)
```
In my case it kept returning `Do you really want to delete the drive item 'testfile.txt'? (yes/No/cancel)` (uh, yes, hehe). 

I'm trying to use this as part of a data processing pipeline and the need to manually confirm kinda wrecks that. Great library; thank you.

**Comment by mpr1255** [comment]
With apologies, of course I meant `confirm = F` and that indeed works as intended. (However, I cannot delete items that are already open ['locked']... which is too bad. I'll come up with workarounds.)

**Comment by hongooi73** [comment]
Note that when you use Microsoft365R in an unattended pipeline, it should never ask for confirmation anyway. Ideally you would be doing that by logging in using one of the methods described in the [vignette](https://cran.r-project.org/web/packages/Microsoft365R/vignettes/scripted.html).
