### ISSUE TITLE
All recipients must be resolved

### ISSUE THREAD

**Issue by coquito77** [Azure/Microsoft365R#119]
I get the error below when I use a business outlook account

     Error in process_response(res, match.arg(http_status_handler), simplify) : 
       Bad Request (HTTP 400). Failed to complete operation. Message:
     At least one recipient is not valid., Recipient 'good_email@test.com' is not resolved. All recipients must be resolved
     before a message can be submitted

The email works fine and it is sent when I use my computer's Outlook application but not when I use the web based Outlook application

**Comment by hongooi73** [comment]
I can send messages to invalid addresses from a personal Outlook account, so this is probably something to do with how business Outlook/Exchange handles invalid addresses. I can't do anything about that.
