### ISSUE TITLE
Sending emails encrypted with Egress

### ISSUE THREAD

**Issue by yungwai-chan** [Azure/Microsoft365R#121]
Hi team,

Thanks a lot for developing this useful package. I have gone through the documentation and various functions, but can't seem to find a way to send emails with this package that would allow encryption by [Egress](https://www.egress.com/) (for which my organisation is using). Is there such an option right now?

Best wishes,
Yung-wai

**Comment by hongooi73** [comment]
Hi, I don't know anything about Egress so I can't really comment on whether it's possible. You can ask them if they use the standard Graph APIs to work with Exchange/Outlook.

**Comment by yungwai-chan** [comment]
@hongooi73 the company replies and unfortunately they don't use standard Graph APIs to work with Exchange/Outlook.

**Comment by hongooi73** [comment]
Yeah, that's unfortunate. Microsoft365R works via the standard API, so there's not much I can do.
