### ISSUE TITLE
Can't upload a file to replace an existing file

### ISSUE THREAD

**Issue by CreRecombinase** [Azure/Microsoft365R#124]
From reading the [Microsoft Graph docs](https://docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=javascript#http-request-to-replace-an-existing-item), it looks like it should be possible to overwrite a drive item with new file contents (i.e to call "upload" on a pre-existing file), but it looks like that isn't currently supported in the R package, are there plans to add this? Thanks!

**Comment by hongooi73** [comment]
Replacing an existing file should work without problems. What happens when you try it?

**Comment by CreRecombinase** [comment]
The error I get looks like this:
```
> gb <- get_business_onedrive(auth_type="device_code")
Loading Microsoft Graph login for default tenant
> gb$upload_file(src = "inst/foo.docx",dest = "Documents/foo.docx")
Error in process_response(res, match.arg(http_status_handler), simplify) : 
  Conflict (HTTP 409). Failed to complete operation. Message:
A file with the same name is currently being uploaded. Change the filename and try to save again.
```

**Comment by hongooi73** [comment]
That's probably an issue on the backend. Wait a few minutes (hours?) and try again.
