### ISSUE TITLE
list_chats() needs additional admin approval

### ISSUE THREAD

**Issue by zekePhoenix** [Azure/Microsoft365R#127]
My IT department has already granted permission to use Microsoft365R. As far as I can tell, all the fucntions within Microsoft365R work. 
Example of a function that works is:
> `list_teams()`
Loading Microsoft Graph login for default tenant

And then I can work with the teams function. 

Ths issue is with `list_chats()`
When I call this function I get:
```
Loading Microsoft Graph login for default tenant
Using authorization_code flow
Creating Microsoft Graph login for default tenant
Using authorization_code flow
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
```
Then in the browser:
![image](https://user-images.githubusercontent.com/47169570/182439037-49236cc3-2644-4119-90cd-188f6c41f0aa.png)

Is this a bug? Or do I need IT to grant additonal permissions?

Thanks.

**Comment by zekePhoenix** [comment]
Any update on this issue?

**Comment by jjesusfilho** [comment]
I use cli for Microsoft 365 and have no issue with admin approval, but with R I get the same message.

**Comment by hongooi73** [comment]
Sorry for the late reply: working with chats requires the Chat.ReadWrite permission, which isn't included in the default list of permissions for the Microsoft365R app ID. I believe you can get your admin to add this permission manually, but I'm not sure what the process is.

**Comment by zekePhoenix** [comment]
Thanks for looking into it. I'll check with our Global Admins and see what they say. Thanks again.

**Comment by hongooi73** [comment]
I think the best solution is to register your own app ID with the permissions you need. Or rather, get them to register it for you, as it's unlikely you'll have the permissions to do so.
