### ISSUE TITLE
`list_teams()`error 

### ISSUE THREAD

**Issue by balthasars** [Azure/Microsoft365R#128]
I cannot get `list_teams()` to work — I get an internal server error. 
Any idas on how to resolve this?
Thanks in advance!
``` r
library(Microsoft365R)
list_teams()
#> Loading Microsoft Graph login for default tenant
#> Error in process_response(res, match.arg(http_status_handler), simplify): Internal Server Error (HTTP 500). Failed to complete operation. Message:
#> Unable to find target address.
```

<sup>Created on 2022-08-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by balthasars** [comment]
This error appears to occur when accessing a resource without the appropriate permissions/license or a personal account (see f.e. [here](https://docs.microsoft.com/en-us/answers/questions/472598/500-response-from-endpoint.html)).

Maybe the developers could consider more meaningful error messages when working with the API?

**Comment by hongooi73** [comment]
The error message is actually straight from the underlying Microsoft Graph API; the R package just passes it through.

Since it appears you've found the source of the problem, I'm closing this. Add a comment if you're still having problems.
