### ISSUE TITLE
Trouble with `list_shared_items()`

### ISSUE THREAD

**Issue by juliasilge** [Azure/Microsoft365R#129]
Hello! 👋  We are digging into why pins users are having trouble sharing via OneDrive as outlined in rstudio/pins-r#588. To explore the problem, @machow and I have been creating items to share with each other but have not had success. We can successfully create a link via `od$get_item("board_to_share_with_michael")$create_share_link("edit", expiry = NULL)` but we have not been able to successfully use that link on the other side. What is the right process for this?

``` r
library(Microsoft365R)
od <- get_personal_onedrive()
#> Loading Microsoft Graph login for tenant 'consumers'
od
#> <Personal OneDrive of Julia Silge>
#>   directory id: 1e1711bbd93e82f4 
#> ---
#>   Methods:
#>     create_folder, create_share_link, delete, delete_item,
#>     do_operation, download_file, get_item, get_item_properties,
#>     get_list_pager, list_files, list_items, list_shared_files,
#>     list_shared_items, open_item, set_item_properties,
#>     sync_fields, update, upload_file

## why does this error in this way?
od$list_shared_items()
#> Error in `[.data.frame`(df, c("name", "size", "isdir", "remoteItem")): undefined columns selected
```

<sup>Created on 2022-08-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Thank you so much for all your work on this! 🙌

**Comment by zhengzheli** [comment]
Maybe try using list_shared_items(allow_external = TRUE)

**Comment by juliasilge** [comment]
Unfortunately, that does not seem to help:

``` r
library(Microsoft365R)
od <- get_personal_onedrive()
#> Loading Microsoft Graph login for tenant 'consumers'
od
#> <Personal OneDrive of Julia Silge>
#>   directory id: 1e1711bbd93e82f4 
#> ---
#>   Methods:
#>     create_folder, create_share_link, delete, delete_item,
#>     do_operation, download_file, get_item, get_item_properties,
#>     get_list_pager, list_files, list_items, list_shared_files,
#>     list_shared_items, open_item, set_item_properties,
#>     sync_fields, update, upload_file
od$list_shared_items(allow_external = TRUE)
#> Error in `[.data.frame`(df, c("name", "size", "isdir", "remoteItem")): undefined columns selected
```

<sup>Created on 2023-04-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hongooi73** [comment]
Hi there, sorry for the delay. I'm looking at this issue now, unfortunately I no longer have access to a business MS365 account. Can you email me (package contact address) so we can set something up? @juliasilge

**Comment by hongooi73** [comment]
#149
