### ISSUE TITLE
Sending custom email content to multiple recipients via tibble

### ISSUE THREAD

**Issue by busmansholiday** [Azure/Microsoft365R#132]
Using Microsoft365R and its email functionality, is there a method to start with a tibble of recipients, subject lines and content (as fields) and to then pass these fields to create$email?  
e.g.

#I have already authenticated

library(Microsoft365R)

test_custom_email <-tibble(
  to = c("a@xyz.com", "b@xyz.com"),
  content = c("This is content A", "This is content B."),
  subject= "Further Email tets from test environment"
)
test_custom_email

I am looking for a syntax that would take these tibble columns as inputs and send the (differentiated content) to the appropriate user? Ideally it would take the process right through to "send".

Thanks in advance,

**Comment by eitsupi** [comment]
It may be the `pwalk` function in the `purrr` package that you are looking for.
https://purrr.tidyverse.org/reference/map2.html

**Comment by hongooi73** [comment]
This is a generic R coding question, not a package issue. Consider asking on the RStudio/Posit forum, or StackOverflow.
