### ISSUE TITLE
Cannot launch Microsoft 365 from RSW

### ISSUE THREAD

**Issue by yacaslimi** [Azure/Microsoft365R#135]
Hello,

I'm working on RSW.  I've downloaded and installed Microsoft365R. I tried to use the get_business_outlook function.

library(Microsoft365R)
my_outlook <- get_business_outlook()

![image](https://user-images.githubusercontent.com/105648250/194265969-2d989f54-940c-4763-b6ff-52efa3f0966a.png)

When I'm launching it, I get a pop-up with the selection of my Microsoft account, and finally,  get a new tab with the following URL 
![image](https://user-images.githubusercontent.com/105648250/194266401-396c270f-0294-4ec7-8277-8b3c126f4d04.png)

As I'm working on the server, the link is not functional. I'm wondering how to modify the parameters of the function/RSW to be able to launch that page on the server.

**Comment by Osteribo** [comment]
Having the same issue. I have been using the package for a while and this has not been an issue before.

**Comment by hongooi73** [comment]
I'm not familiar with RSW. You should ask this on the RStudio community forums, or contact RStudio's tech support directly, as this doesn't seem to be a bug in Microsoft365R as such.

**Comment by hongooi73** [comment]
Late comment: RSW is a remote server, so you have to authenticate using the device_code flow. Like this:

```
get_business_outlook(auth_type="device_code")
```

See ?get_business_outlook, in particular the 2nd paragraph under "Details".
