### ISSUE TITLE
Copy drive item?

### ISSUE THREAD

**Issue by CreRecombinase** [Azure/Microsoft365R#137]
It would be really cool if the [copy drive item API](https://learn.microsoft.com/en-us/graph/api/driveitem-copy?view=graph-rest-1.0&tabs=http) was exposed. Any interest in a pull request?

**Comment by hongooi73** [comment]
A PR would be great!

**Comment by hongooi73** [comment]
This turned out to be fairly simple, so I've gone ahead and added it.
