### ISSUE TITLE
Can you access a SharePoint site without following it?

### ISSUE THREAD

**Issue by KyleHaynes** [Azure/Microsoft365R#146]
From the Readme:

> SharePoint Online
To access a SharePoint site, use the get_sharepoint_site() function and provide the site name, URL or ID. You can also list the sites you're following with list_sharepoint_sites().

Unless I'm missing something, or it's a tenancy setting(?) you can only `get_sharepoint_site()` if you're following the actual site. 

Is this assumption correct, because I can't seem to see anything in the doco that suggest it necessarily being true?

**Comment by taylo5jm** [comment]
@KyleHaynes I believe you can use `get_sharepoint_site` on any Sharepoint site you have access to, regardless of whether or not you are following it. The `list_sharepoint_sites` function, however, only shows the Sharepoint sites you are following.

- Justin

**Comment by KyleHaynes** [comment]
@taylo5jm,
I don't think so, at least not on our instance (where I work). Will test Monday and get back to you. Thanks

**Comment by KyleHaynes** [comment]
@taylo5jm - confirming a colleague can, but I can't. Closing as it must be related to my setup.
