### ISSUE TITLE
Conflict (HTTP 409) error when using upload_file()

### ISSUE THREAD

**Issue by macsmith26** [Azure/Microsoft365R#15]
Hello,

Received this error when trying to upload a file using `upload_file()` to our SharePoint site: `  Conflict (HTTP 409).` The method did create a temp file in the directory I specified with the same file size as the uploaded file, but I can only see the temp file when I access the SharePoint drive as a mapped network drive. I've authenticated using Azure CLI's app ID.

**Comment by hongooi73** [comment]
That's probably because somebody else was working with a file of the same name. Try uploading again later, or use a different file name.

**Comment by macsmith26** [comment]
The issue was on my part. I wasn't specifying the file location properly. Function works as intended.
