### ISSUE TITLE
Microsoft365R opens up a blank page.

### ISSUE THREAD

**Issue by mxshiv** [Azure/Microsoft365R#163]
Hello. Am reaching out to you to get your assistance in looking into getting access to IM on Workbench. The Workbench is configured on a RHEL system.

We are using the ‘Microsoft365R’ package. Authorisation is triggered by just trying to use the app:
library(Microsoft365R)
list_sharepoint_sites()

On Workbench, the localhost page is not working to finish off the authorisation. 

Looking forward to your support. Many thanks.

http://[localhost](http://localhost:1410/ => shows a blank page
![MS365R Web Page](https://github.com/Azure/Microsoft365R/assets/127917172/b81c0b07-3372-4741-a1af-1f0742090a3f)

**Comment by hongooi73** [comment]
This is addressed in the [authentication vignette](https://cran.r-project.org/web/packages/Microsoft365R/vignettes/auth.html), although it could probably be made clearer. You have to use the device_code flow when authenticating in an R session running anywhere other than on your local machine.

```
list_sharepoint_sites(*, auth_type="device_code")
```

**Comment by mxshiv** [comment]
Thanks a ton for your kind help. I was able to authenticate on Workbench using your advice. This required to then manually going to a separate browser window, and entering a code, then entering my email address, then approving on authenticator, then confirming etc. So, it’s a bit of a process, though it does work. 

Would SAML approach be an alternate option that could be more seamless for the same outcome?

Aso, I have a similar query for Connect and Shiny app as well. Will open another thread for the same.

Thanks.

**Comment by hongooi73** [comment]
SAML isn't supported; I don't really know much about it. It could be added to AzureAuth (the package that handles authentication for all the AzureR packages) if there's enough demand.

**Comment by mxshiv** [comment]
Understood. Thanks.

I need to be able to use MS365R on Posit Connect host as well (RHEL 8). Can you please guide me to the correct procedure to make it work? Many thanks.
