### ISSUE TITLE
MS365R on Posit Connect 

### ISSUE THREAD

**Issue by mxshiv** [Azure/Microsoft365R#168]
Can you please guide me on using the MS365R on Posit Connect? Thanks.

I was able to authenticate on Workbench using the advice I got back from this forum but I believe that Connect will probably require a different approach. In the main authentication vignette ([Authenticating to Microsoft 365 (r-project.org)](https://cran.r-project.org/web/packages/Microsoft365R/vignettes/auth.html) ) it says:

If you want to use Microsoft365R outside a local R session, creating a custom app registration is required. In particular, this includes the following common scenarios:
o	Using Microsoft365R inside a Shiny webapp
o	Using it in an unattended (automated) script, eg in a GitHub Actions workflow or other CI/CD pipeline

See the vignettes “Using Microsoft365R in a Shiny app” and “Using Microsoft365R in an unattended script” for more on these use cases, including how to configure the app registration in Azure Active Directory.

The first vignette [Using Microsoft365R in an unattended script (r-project.org)](https://cran.r-project.org/web/packages/Microsoft365R/vignettes/scripted.html) does seem to start talking about service accounts as an option which is something we would like to test as well.

The second one on Shiny specifically ([Using Microsoft365R in a Shiny app (r-project.org)](https://cran.r-project.org/web/packages/Microsoft365R/vignettes/shiny.html)) seems to talk about individual authorisation per Shiny application. 

Though I am a bit confused as to whether this then tries to use individual permissions in that app, vs what we want is more the service account approach so that the application has a certain set access regardless of who uses it. And also ideally I think we would prefer a solution that allows the service account for all apps without needing to manually approve each one?

Can you please guide? Many thanks.

Regards

**Comment by mladencucak** [comment]
Any progress on this?

**Comment by mxshiv** [comment]
Is it ok to test the first vignette [Using Microsoft365R in an unattended script (r-project.org)](https://cran.r-project.org/web/packages/Microsoft365R/vignettes/scripted.html)?

**Comment by hongooi73** [comment]
I don't know what Posit Connect is. Is that the new name for Rstudio workspaces, ie running R on a remote shared server? If so, you shouldn't need to create a new app ID. Just authenticate with the device_code authflow; see the authentication vignette for more on this.

**Comment by mladencucak** [comment]
POSIT is the new name for RStudio company. Although the tool still has the same name.

**Comment by mladencucak** [comment]
POSIT = RStudio
