### ISSUE TITLE
rJava fails to load.

### ISSUE THREAD

**Issue by mxshiv** [Azure/Microsoft365R#170]
While trying to load rJava, it complains of a missing shared object file. I have installed the system pre-requisites as per the package description and still no luck. Can you please help? Many thanks.

# dnf install -y make
# dnf install -y java-1.8.0-openjdk-devel
# R cmd javareconf
# yum install java-1.8.0-openjdk-headless java-11-openjdk-headless java-17-openjdk-headless java-17-openjdk-17* yum install java-11-openjdk-11*

======================================================================================
> library('rJava')
Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/home/mxshiv/R/x86_64-pc-linux-gnu-library/4.2/rJava/libs/rJava.so':
  libjvm.so: cannot open shared object file: No such file or directory
=====================================================================================

**Comment by hongooi73** [comment]
Not related to Microsoft365R. Did you post to the wrong tab in your browser?

**Comment by mxshiv** [comment]
Apologies. It indeed was posted in the wrong tab.
