### ISSUE TITLE
SSL peer certificate or SSH remote key - Remote certificate not trust

### ISSUE THREAD

**Issue by zshi0004** [Azure/Microsoft365R#172]
Hi.

We have encounter a error while using the package. Please see our error message below.

>  `list_sharepoint_sites()`
> Using authorization_code flow
> Creating Microsoft Graph login for default tenant
> Using authorization_code flow
> Waiting for authentication in browser...
> Press Esc/Ctrl + C to abort
> Authentication complete.
> AzureR data directory does not exist; login credentials not saved
> Error in curl::curl_fetch_memory(url, handle = handle) : 
>  SSL peer certificate or SSH remote key was not OK: [graph.microsoft.com] schannel: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.

We are able to access graph.microsoft.com and have updated the global  and intermediate certificates. After updating certificates, we still encounter the same error. We are using the package from RStudio desktop.

Wonder if there is a solution for us to solve this issue and get access to SharePoint.

Thank you.

**Comment by hongooi73** [comment]
This is an issue with the curl package configuration, or a proxy somewhere between you and Microsoft. Either way, it's unrelated to Microsoft365R. Consider asking on the RStudio/Posit community forums or Stackoverflow.
