### ISSUE TITLE
Cannot Download Files from Onedrive

### ISSUE THREAD

**Issue by hongyileoxu** [Azure/Microsoft365R#175]
Thank you in advance. 

I am very new to this and currently using Rstudio Server to do some data work. I have successfully connect my business Onedrive with Rstudio server and can find see the files in Onedrive. However, when I try to download the file from Onedrive, e.g. `my_onedrive$download_file("SHoF/2021_info.zip", overwrite = T)`, it gives me the following error message: 

> Error in curl::curl_fetch_disk(url, x$path, handle = handle) : Failed writing body (5814 != 16384). 

Meanwhile, a file with this name will show up in the directory but cannot be opened and 0 file size. 

This issue seems not to link to the file size. I also updated the "curl" packages and the issue did not go away. 

Did anyone encounter the same issue? Really appreciated.

**Comment by raahlstrom** [comment]
I am having the same issue. It will eventually work if I run download_file multiple times, but I can't get it to consistently work on the first few tries.

**Comment by hongooi73** [comment]
Since you can eventually download successfully, this indicates that Microsoft365R is working and the problem is in a lower-level package, most likely curl. I'm not sure what to do about this, but you can ask for help on the Posit/Rstudio forum, or post an issue on the curl repo.
