### ISSUE TITLE
"By" parameter in list_emails() not working

### ISSUE THREAD

**Issue by iagocnunes** [Azure/Microsoft365R#176]
Hi, both "received" and "received desc" are returning the same email. Is there a problem with the function?
```
library(Microsoft365R)
my_outlook <- get_business_outlook()
email <- my_outlook$list_emails(by = "received desc", filter = "startswith(sender/emailAddress/address,'test')", n = 1)
email <- my_outlook$list_emails(by = "received", filter = "startswith(sender/emailAddress/address,'test')", n = 1)
```

**Comment by hongooi73** [comment]
The `by` arg only works if you don't supply `filter` and `search`; see the documentation for `?ms_outlook_folder`. This is a limitation of the underlying Graph API.
