### ISSUE TITLE
Auth issue 

### ISSUE THREAD

**Issue by HarshalRepo** [Azure/Microsoft365R#179]
I am trying to authenticate as I am using this Package on my company's Rstudio Workbench.

When I refer inst/app_registration.md, I am not understanding which tenant they need to provide access. My Company Administrator asking me for what application, They need to grant me access? Do I need to create tenant for me & then admin needs to give access.

Apology as I am struggling to get through authentication since long time & this package serves my purpose hence your support would be helpful for me.

**Comment by hongooi73** [comment]
This isn't technically related to Microsoft365R. You can try asking for help on Stackoverflow or the Posit/Rstudio forum.
