### ISSUE TITLE
Error when accessing Sharepoint site: site not found

### ISSUE THREAD

**Issue by emmalink1** [Azure/Microsoft365R#180]
I have been able to use this package to access files in my work OneDrive account but have been unable to access my employer's Sharepoint site. When I run:
site <- get_sharepoint_site("https://practicalfarmers.sharepoint.com/")

 I get the following error: 

Error: Site 'https://practicalfarmers.sharepoint.com/' not found.

This my employers exact Sharepoint url; is there another way that I'm supposed to format it?

**Comment by RPanczak** [comment]
I always get more luck with `device_code` authentication @emmalink1 

`site <- get_sharepoint_site(site_url = "https://practicalfarmers.sharepoint.com/",  auth_type = "device_code")`

**Comment by hongooi73** [comment]
@emmalink1 I don't have access to Sharepoint right now, but typically a site is not the top-level URL; it will instead be something like "practicalfarmers.sharepoint.com/sites/my-site-name".
