### ISSUE TITLE
Local Host Can't be reached when attempting to use get_sharepoint_site() from Rstudio Server

### ISSUE THREAD

**Issue by AlexHakansson** [Azure/Microsoft365R#181]
![image](https://github.com/Azure/Microsoft365R/assets/22452674/a24ad6ac-9434-489b-8a00-1359aa4760d1)

Hello, I am attempting to use the get_sharepoint_site() from my rstudio server. I can run it locally but when I try to run it from the server I get localhost refused to connect. I have seen some things online about going to "Azure Active Directory" to get a token but I personally don't have access to this. Is there a way to use get_sharepoint_site() from the RStudio server without using Azure Active Directory?

**Comment by hongooi73** [comment]
See the "Authentication" vignette; you have to use the device code auth flow when running on RStudio Server.

```
get_sharepoint_site("site", ..., auth_type="device_code")
```

In general, support questions should be asked somewhere else, like Stackoverflow or the RStudio/Posit forums. Issues should be for reporting bugs or making feature requests.

**Comment by AlexHakansson** [comment]
Thanks this was helpful!
