### ISSUE TITLE
Azure AD account, tenant, shared R scripts

### ISSUE THREAD

**Issue by Chicago-Dave** [Azure/Microsoft365R#183]
Don't know where else to ask this question. 
Scenario: 

- R scripts shared by four people. 
- Various reports with Teams deliveries, Outlook deliveries
- Outlook deliveries now use shared email for our office ('research@') 

Does each person need to establish an Azure AD account? Or can other email addresses be added to the established tenant list?

We have no app development needs. Couldn't get MS365R to work without creating Azure AD account. Reading up on Azure, lots of it does not apply. Any direction or suggested reading appreciated.

**Comment by hongooi73** [comment]
You're best off talking to your MS rep, if you have one; I'm not really an AAD/Entra specialist. However, each person should have their own AAD account. You should already have this, in fact, if you're using Teams/Outlook/etc. I assume 'research' is a shared Outlook inbox, in which case you should be able to get Microsoft365R to read it. You will need to register your use of the package as an app in AAD, though. (This is where an AAD specialist would really help.)
