### ISSUE TITLE
Issue with downloading shared files. 

### ISSUE THREAD

**Issue by RealcoJaneZheng** [Azure/Microsoft365R#189]
Hi! I found your package really handy but after I updated the package from version 2.3.4 to the latest version, seems I cannot properly download shared files anymore. 

For example, if I want to download the first item of the shared files, this is what I did with version 2.3.4 and it worked very well. 
`drv <- get_business_onedrive()`
`drv$list_shared_items("items")[[1]]$download(dest = "test.csv", overwrite = TRUE)`

After updating the package, this is what I did. 
`drv <- get_business_onedrive()`
`drv$list_shared_items()[[1]]$download(dest = "test.csv", overwrite = TRUE)`

I can still successfully download a file, but the file is not the same as the original file. The original file is a csv file with a dataframe. However, this is a screenshot of a part of the file I downloaded. 

<img width="1253" alt="Screenshot 2023-10-31 at 5 00 05 PM" src="https://github.com/Azure/Microsoft365R/assets/61711939/e63ce60f-5dd2-4f7c-8af4-140efbb12f8c">

Is this the correct way to download a shared file? Was there anything I did wrong? Thank you very much in advance for your help!

**Comment by SHogenboom** [comment]
@RealcoJaneZheng  have you been able to find a workaround yet? I’m having the same issue and it’s rather inconvenient!

**Comment by SHogenboom** [comment]
@RealcoJaneZheng Thanks! Might consider that as well. For now I created a shortcut to the parent_folder which is connected to my individual drive. Then I can use the normal ‘get_item’ approach. Not ideal tbh, but sufficient for now.

**Comment by hongooi73** [comment]
Are people still experiencing this bug? Shared items in Business Outlook is hard for me to debug, since I don't have access to a business MS365 account right now.

**Comment by hongooi73** [comment]
@elipousson does your sharepointr package have the same problem?

**Comment by elipousson** [comment]
@hongooi73 I actually hadn't tried the `list_share_items()` method previously but I am encountering what seems to be a similar error. I do have a batch download function in my own package but it uses `get_item` and then uses the `download` method on the item.

So far, I can't tell the difference (if there is any) between an element of the list created with `list_shared_items()` and `get_item()` but one works and the other doesn't.

**Comment by hongooi73** [comment]
> So far, I can't tell the difference (if there is any) between an element of the list created with list_shared_items() and get_item() but one works and the other doesn't.

@elipousson The info returned by Graph is all in the `properties` field of the R6 object. If you compare this field in the objects returned by `get_item` and `list_shared_items`, do you see any difference?

**Comment by hongooi73** [comment]
The 'shared-item-fix' branch reverts the code to what it was in the earlier version. Can people affected by this give it a go, and tell me if it works?

**Comment by hongooi73** [comment]
@elipousson @SHogenboom @RealcoJaneZheng is the fix working?
