### ISSUE TITLE
Obtaining a file URL

### ISSUE THREAD

**Issue by reed-klein** [Azure/Microsoft365R#195]
Is it possible to include functionality for retrieving a file's SharePoint URL based on the file name? For example, $list_files() will give me the names in a folder; I could then use one or more of those names to obtain the relevant file URLs (note: this is the URL as it appears when clicking "Copy link", or "Share link" for a file in SharePoint--not the URL as it appears in the web browser's address bar).

Many thanks for all of the work on this package--it is fantastic!

**Comment by hongooi73** [comment]
Do you mean a link that you would share to someone outside your team? If so, the `create_share_link()` method is what you're looking for.

**Comment by reed-klein** [comment]
That works! Thanks so much!

**Comment by reed-klein** [comment]
That works! Thanks so much!
