### ISSUE TITLE
business_onedrive() cannot access files due to incorrect permissions on app

### ISSUE THREAD

**Issue by leungi** [Azure/Microsoft365R#2]
Reproducible example below.

Is there some settings in OneDrive that may be checked to see if issue is to do with permission?

```r
library(Microsoft365R)
odb <- business_onedrive()
#> Loading Microsoft Graph login for default tenant
odb$list_items()
#> [1] name  size  isdir
#> <0 rows(or 0-length row.names)
odb$list_files()
#> [1] name  size  isdir
#> <0 rows(or 0-length row.names)
odb$create_folder("test")
#> Error in process_response(res, match.arg(http_status_handler), simplify) : 
#>   Forbidden (HTTP 403). Failed to complete operation. Message:
#> Access denied.
```

**Comment by hongooi73** [comment]
Hi, thanks for using the package. Just to confirm, do you have files in your business OneDrive? Are you able to create directories and files in Explorer?

You can also see if using an explicit tenant works: `odb <- business_onedrive(tenant="yourtenant")`

**Comment by leungi** [comment]
@hongooi73 : thank you for creating the 📦 ! Being able to access Sharepoint List is already a bonus 😄 

To your questions:

- I do have files in the OneDrive, and I have full control permission (refer to .gif below)

![od-test](https://user-images.githubusercontent.com/30273868/104818655-90511d00-57ee-11eb-98f2-31f0bdf152a3.gif)

- tried with explicit tenant; authentication OK as before, but still showing empty.

```r
odb <- business_onedrive(tenant="oxyinc")
#> Using authorization_code flow
#> Creating Microsoft Graph login for tenant 'oxyinc.onmicrosoft.com'
#> Using authorization_code flow
#> Waiting for authentication in browser...
#> Press Esc/Ctrl + C to abort
#> Authentication complete.
odb$list_files()
#> [1] name  size  isdir
#> <0 rows> (or 0-length row.names)
odb$list_items()
#> [1] name  size  isdir
#> <0 rows> (or 0-length row.names)
```

**Comment by hongooi73** [comment]
Ok, I can confirm this. It looks like the Az CLI which I'm piggybacking off allows SharePoint access, but NOT OneDrive for Business.

Can you see if either of the following work? You'll get a dialog box asking for permission to access your info.

```
gr <- AzureGraph::create_graph_login(tenant="oxyinc",
    app="d44a05d5-c6a5-4bbb-82d2-443123722380",
    scopes="Files.ReadWrite.All")
drv <- gr$get_user()$get_drive()
drv$list_items()


gr <- AzureGraph::create_graph_login(tenant="oxyinc",
    app="5bb21e8a-06bf-4ac4-b613-110ac0e582c1",
    scopes="Files.ReadWrite.All")
drv <- gr$get_user()$get_drive()
drv$list_items()
```

**Comment by leungi** [comment]
Thanks for investigation.

Just what I'm afraid of, I don't think my current account privileges allow testing your suggestions.

Let me get with internal Azure support team to carry out your experiments.

![od-cl-test](https://user-images.githubusercontent.com/30273868/104820221-08bcdb80-57f9-11eb-8c74-eef78268c4fe.gif)

**Comment by hongooi73** [comment]
Did they both fail with that message?

**Comment by leungi** [comment]
Yes, both asked for admin auth.
On Jan 16, 2021, 12:50 PM -0600, Hong Ooi <notifications@github.com>, wrote:

WARNING - This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.

________________________________

Did they both fail with that message?

**Comment by hongooi73** [comment]
I've changed the app registration; the current one will run into issues with not being a verified publisher. If your support team asks, the new app ID is **d44a05d5-c6a5-4bbb-82d2-443123722380**

You'll also have to reinstall the package to use the new ID. Sorry for the inconvenience.

**Comment by hongooi73** [comment]
Microsoft365R now consistently uses its own app ID by default, for both OD and SPO. This fixes access to OD for Business, at the cost of potentially requiring approval from an admin.

You can still get the old SPO behaviour (which was technically not very kosher) by using the `app` and `scopes` arguments to `sharepoint_site`:

```r
sharepoint_site("https://mycompany.sharepoint.com/sites/my-site-name",
     app=AzureGraph:::.az_cli_app_id,
     scopes=".default")
```

Note that this may draw the attention of your admin!

**Comment by leungi** [comment]
You almost did it! Why didn't I think OneDrive is SPO in disguise, like Teams 😅 

I suspect there's a setting to completely lock out OD.

# Still listing zero files
```r
> spo$get_drive()
<Document library 'OneDrive'>
  directory id: b!UUgs_h5klkyzjHsQ-ULCHHu1fE9UJglJojHmp5RseSUy0lqsOyN7RYEYUzyblWak 
  web link: https://oxyinc-my.sharepoint.com/personal/ivan_leung_oxy_com/Documents 
  description:  
---
  Methods:
    create_folder, create_share_link, delete, delete_item, do_operation, download_file,
    get_item_properties, list_files, list_items, open_item, set_item_properties, sync_fields,
    update, upload_file
> od <- spo$get_drive()
> od$list_items()
[1] name  size  isdir
<0 rows> (or 0-length row.names)
> od$list_files()
[1] name  size  isdir
<0 rows> (or 0-length row.names)
```

On a positive note, you did @MSFT a service - due to this, IT is going to set up Azure blob instead 😀 

Thanks again for your time investigating this 🙇

**Comment by hongooi73** [comment]
What is the printout from `spo$token`?

**Comment by leungi** [comment]
I presume you're after the app Id - `App ID: 04b07795-8ddb-461a-bbee-02f9e1bf7b46`

**Comment by hongooi73** [comment]
That is the Azure CLI app id, which does NOT work with ODB. You'll need to use (and get approved) the Microsoft365R app ID, which is the new default just pushed.

**Comment by leungi** [comment]
I see.

I’ll try making the request internally again, but I feel they’ll push me to Azure blob again.

Thanks again!

**Comment by hongooi73** [comment]
Just a couple comments:

- You should be able to access ODB on Windows natively, if you've synced it with a folder on your local disk. You don't need to use this package if so.
- For Azure storage, you can use AzureStor to access blob storage; or if you use file storage, there is also the option to mount it as a drive in Windows.

**Comment by leungi** [comment]
Points noted.

Current use case is to access OD in a Linux VM 🙂

**Comment by hongooi73** [comment]
Actually, can you try another app ID:

**31359c7f-bd7e-475c-86db-fdb8c937548e**

This is the app ID for the [CLI for Microsoft 365](/pnp/cli-microsoft365). Still piggybacking off someone else, but this one is likely to be already in use in your org.

**Comment by leungi** [comment]
@hongooi73 , I appreciate your persistence 🙏 

Unfortunately, it still requires admin approval to Azure Resource.

Another note, even SharePoint connection faces the same issue (needing admin privileges to authenticate) with the latest commit:

- `Microsoft365R * 1.0.0   2021-01-22 [1] Github (Azure/Microsoft365R@96bd0b2)`

**Comment by hongooi73** [comment]
Ok, thanks. The CLI is not a first-party app so it still requires approval.

To get Sharepoint back, authenticate like this:

```r
sharepoint_site("https://your-site", app=AzureGraph:::.az_cli_app_id)
```

**Comment by leungi** [comment]
When there's a will, there's a way 😁 

Your 📦 + Microsoft Flow (OneDrive > SharePoint).

```
> drv <- site$get_drive()

> drv$list_items()
      name    size isdir
1  General 4689885  TRUE
2  project   69196  TRUE
3 lbtc.png   25347 FALSE

> drv$list_items("project")
                                    name  size isdir
1 2018-07-24_optimization_well_list.xlsx 69196 FALSE
```

**Comment by hongooi73** [comment]
Is that your Onedrive? Sound intriguing. Can you provide the details?

**Comment by leungi** [comment]
`site` points to my SharePoint site 😅 

#### Workflow:

1. Create a folder in SharePoint where OneDrive files are to be saved to
2. Create a [Flow](https://us.flow.microsoft.com/en-us/galleries/public/templates/958c5ff20efb407e8f22c0568fe1298e/copy-files-between-onedrive-for-business-and-sharepoint/) to automatically copy OneDrive content to folder listed in 1)
3. Use {Microsoft365R} to access SharePoint, in lieu of OneDrive
