### ISSUE TITLE
HTTP Error 400: Bad Request when creating new folder

### ISSUE THREAD

**Issue by DanielBGAtlas** [Azure/Microsoft365R#24]
Hello,

I'm having problems when creating a new folder inside an existing folder. When I create a folder in the root directory of my drive all goes smoothly. For example:

```
drive -> get_personal_onedrive()
drive$create_folder("newfolder")
```
That works perfectly, but when I try:

`drive$create_folder("ExistingFolder/newfolder")`

I get the following error:

```
Error in process_response(res, match.arg(http_status_handler), simplify) : 
  Bad Request (HTTP 400). Failed to complete operation. Message:
Bad Argument.
```
I also tried with `drive$create_folder("/ExistingFolder/newfolder")`, `drive$create_folder("~/ExistingFolder/newfolder")` and several others, but no one worked.

Am I missing something?

Thanks.

**Comment by hongooi73** [comment]
This is because the Graph API doesn't support creating nested directories; you have to create each subdirectory separately. Something like this:

```r
drive$get_item("ExistingFolder")$create_folder("newfolder")
```

I'll see about getting recursive directory creation into the next version.

**Comment by hongooi73** [comment]
> ... so, it turns out that Graph DOES support nested dir creation, it just isn't documented.

Or maybe it doesn't. Creating a nested folder in a single API call works for personal OneDrive, but seems to fail for Business OD and SharePoint.
