### ISSUE TITLE
Support for add mentions to a channel message

### ISSUE THREAD

**Issue by nicholsn** [Azure/Microsoft365R#26]
I'm trying to add a `@mention` to a message that I posted to a channel. 

Looking at the API documentation it looks like the request needs to include a list of `mentions` objects: https://docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&tabs=http#request-1

Is this functionality already supported or do you have suggestions for how I can tag one of my team members in a message?

**Comment by hongooi73** [comment]
This is kind of complicated from a programming perspective, since you need to find the ID of the user and then add it to the both the message body and the `mentions` property (along with other metadata). Right now, the easiest thing to do is probably to manually edit the message in the Teams app after you've posted it.

**Comment by nicholsn** [comment]
Thanks, @hongooi73! It does look a little complicated, but I think with support the [list-members](https://docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&tabs=http) and [get-member](https://docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&tabs=http) endpoints in place it wouldn't be too bad. 

Any chance those are on the roadmap or you'd be open to reviewing a PR that adds them?

**Comment by hongooi73** [comment]
I don't really have a definitive roadmap; I prefer to be guided by what people ask for here. I do intend to add this feature eventually though (probably right after Outlook support is implemented, in fact). Feel free to submit a PR to help speed the process along. 🙃

**Comment by MattBrauer** [comment]
One application of this method could be to notify a user that the results of their automated analysis pipeline were completed. In that case, the user's contact info (including user name, ID and other metadata) could be kept with the script that makes the notification. So no need for an on-the-fly lookup of these values.
