### ISSUE TITLE
unable connect from systems without web browser

### ISSUE THREAD

**Issue by RollieParrish** [Azure/Microsoft365R#3]
When using this package on a Linux server that does not have a desktop environment, (ie. RStudio Server), the authentication via browser fails, as it opens a url to "localhost'. 

The AzureRMR::create_azure_login() function has a parameter of `auth_type='device_code'`, which is useful in this situation. 

Can that be incorporated (some other solution)?

**Comment by RollieParrish** [comment]
Just discovered  that the '*_onedrive()` functions can pass through parameters to AzureGraph::create_graph_login, including `auth_type='device_code``. 

So using `od <- business_onedrive(auth_type = "device_code")` works as expected.

**Comment by IdoBar** [comment]
This seems to work when running the code as a script, but not when knitting RMarkdon file that depends on it and comes up with the following output:
```
Creating Microsoft Graph login for default tenant
Waiting for device code in browser...
Press Esc/Ctrl + C to abort
```
@hongooi73 , any suggestions or should I open a new issue for this?

**Comment by hongooi73** [comment]
If you run the script multiple times, do you have to login each time?

**Comment by IdoBar** [comment]
I double-checked that and there a couple of things:
If I run it with `auth_type='device_code'` (knitting the RMarkdown), it always producing that warning, but I can't see the output with the code to enter.
If I run it without `auth_type='device_code'` it works fine as long as the token is valid (for 1 hour), but after the token has expired it was failing to refresh it.
It is working at the moment, but I'll update if that authentication issue returns.
BTW, it worked just fine until I had to change my organization password last week...

**Comment by hongooi73** [comment]
Clear your token cache as described in #11, and try it again.
