### ISSUE TITLE
outl$list_emails() method

### ISSUE THREAD

**Issue by opus1993** [Azure/Microsoft365R#33]
version 2.0.0 
Outlook mail client functionality

vignette functions properly through compose_email(), outl$create_email(), em$add_attachment(), and em$send()

 outl$list_emails()      returns an empty list for an inbox full of messages

att.net mail

**Comment by hongooi73** [comment]
Do you mean that your primary account is an att.net email address, which you've linked to Outlook?

I should clarify that Microsoft365R works with Outlook-native accounts (ie, Microsoft Exchange), sorry.
