### ISSUE TITLE
Should I be able to read an Excel file without saving a local copy?

### ISSUE THREAD

**Issue by rrodrigueznt** [Azure/Microsoft365R#35]
Hi! I've reached this great development. Thanks for the initiative! Please, is this the right place to ask questions? Far from being a developer myself, I'm currently facing a number of issues within my organization where Azure related packages will be a great help!

Concerning my current issue: I easily find how to download a copy of an Excel file stored in OneDrive - Personal. **Should I be able to read it online**? Please, if yes, could you point me in the right direction?

Thanks!

**Comment by hongooi73** [comment]
Hi there,

There are 2 ways you can use this package to access a worksheet in OD:

- You can use the `open_item()` method to open the file in **Excel Online**. This is the version of Excel that works in your browser. This doesn't download the file to your local machine.
   ```
   drv <- personal_onedrive()
   drv$open_item("path/to/sheet.xlsx"
   ```

- You can use `download_file()` to download the file, and then open it in Excel (assuming you're using Windows).
   ```
   drv <- personal_onedrive()
   drv$download_file("path/to/sheet.xlsx")
   shell.exec("sheet.xlsx")
   ```
