### ISSUE TITLE
Shared Inbox Access?

### ISSUE THREAD

**Issue by shriv** [Azure/Microsoft365R#39]
Hiya, 
I'm a very new user of this package. My particular use case is developing an ETL pipeline which begins with extracting automated data feeds from a Shared Inbox. I've got access to my Outlook mail but I am unable to see the Shared Inbox. I suspect this is because the `Microsoft365R` package only requests `Mail.ReadWrite`  permissions rather than `Mail.ReadWrite.Shared` as per [here](https://stackoverflow.com/questions/63668950/access-shared-mailbox-via-microsoft-graph-access-denied)? Do I need to ask the admin to include this permission separately or would there be an update to this package that will allow Shared Inbox access?

Thanks!

**Comment by hongooi73** [comment]
Hi, thanks for using the package. I haven't looked at shared inboxes before this, but from what I can tell there's a couple of things needed:

- You need to enable the Mail.ReadWrite.Shared permission as noted. You can create a custom app registration that has this permission instead of Mail.ReadWrite (your admin is probably the one to do this). The full list of permissions is [here](https://github.com/Azure/Microsoft365R/blob/master/inst/app_registration.md).
- You have to use the shared inbox ID, rather than your personal mailbox, to read the messages. Unfortunately Microsoft365R doesn't have a built-in way to do this right now, but you can try the following:

```r
library(Microsoft365R)
gr <- AzureGraph::create_graph_login(app="yourappid")  # 'yourappid' is the ID of the app registration you created
shared_inbox <- gr$get_user("inboxid")$get_outlook()
```

Assuming this works, on subsequent calls you can replace `create_graph_login` with `get_graph_login`.

**Comment by shriv** [comment]
Thanks for such a quick reply! :-) 
Just to confirm, I will create an app with all the permissions you have noted [here](https://github.com/Azure/Microsoft365R/blob/master/inst/app_registration.md) and just replace `Mail.ReadWrite` with `Mail.ReadWrite.Shared`? 

Is there a way I can use `Microsoft365R` to send this request? I ask because our org permissions are very locked down and we cannot even access the AAD portal.

**Comment by hongooi73** [comment]
No, you'll have to get your admin to do this. (It's possible that you could use the underlying AzureGraph package to create the app, but if your org is locked down you probably don't have the rights to create apps.)

**Comment by shriv** [comment]
Okay, that makes sense! Thanks :-)

**Comment by hongooi73** [comment]
Also, if shared inbox access is a much-requested feature I can change the default permissions on the Microsoft365R app. I'm leery of doing this right now though, as it would require people to re-authorise the app to access their data.

**Comment by shriv** [comment]
I, for one, would appreciate it but it would be annoying for others! I'll see how I get on with requesting an app in our org tenant..

**Comment by hongooi73** [comment]
Please leave this open as others may also want the same feature.

**Comment by iankloo** [comment]
Just throwing in that I would also benefit from this feature.

**Comment by hongooi73** [comment]
@iankloo You can actually do this right now. You'll have to get your admin to consent to the necessary permissions first, but then you can run something like this:

```r
gr <- AzureGraph::create_graph_login("yourtenant",
    app=Microsoft365R:::.microsoft365r_app_id,
    scopes=c("Mail.ReadWrite.Shared", "Mail.Send", "Group.ReadWrite.All")  # use shared mail scope
)
user <- gr$get_user("username@tenant")
user_mbox <- user$get_outlook()
```
It's just a question of whether and how much this should be automated in Microsoft365R.

**Comment by hongooi73** [comment]
Shared mailbox support has been added to `get_business_outlook`. To retrieve a shared mailbox, supply one of the arguments `shared_mbox_id`, `shared_mbox_name` or `shared_mbox_email`. If you leave all of these out, you will get your own mailbox (the current behaviour).

Note that shared access requires extra permissions, namely Mail.Send.Shared and Mail.Readwrite.Shared. You'll get a message asking your admin to approve this.

**I'm unable to test this as I don't have access to a suitable tenant/mailbox right now, so can those who requested this feature please try it out and tell me if there are any problems. Thanks!**

**Comment by hongooi73** [comment]
@isaac-florence @iankloo @shriv

**Comment by hongooi73** [comment]
Now in 2.3.0

**Comment by isaac-florence** [comment]
Hi @hongooi73, please accept my apologies for not thanking you here sooner. Our security team have only just reapproved the app and I can confirm this works just as expected for us. Thank you very much for implementing this change, it's hugely appreciated.

**Comment by mmadmar** [comment]
Hi @hongooi73 
Thank you for the great package.

I use the following snippet: 
`my_outlook <- get_business_outlook(
  tenant = tenant,
  app = app,
  shared_mbox_name = "shared@xyz.com",
  password = client_secret,
  auth_type="client_credentials"
)`

This gives the following error
`Loading Microsoft Graph login for tenant 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
Creating Microsoft Graph login for tenant 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
Error in process_aad_response(res) : 
  Bad Request (HTTP 400). Failed to obtain Azure Active Directory token. Message:
AADSTS1002012: The provided value for scope https://graph.microsoft.com/User.Read https://graph.microsoft.com/Mail.Send https://graph.microsoft.com/Mail.ReadWrite https://graph.microsoft.com/Mail.Send.Shared https://graph.microsoft.com/Mail.ReadWrite.Shared openid offline_access is not valid. Client credential flows must have a scope value with /.default suffixed to the resource identifier (application ID URI).
Trace ID: xxxxxxxxxxxxxx
Correlation ID: xxxxxxxxxxxxxxxxxxxx
Timestamp: xxxxxxxxxxxxxxxxxx.`

Can you help with that?

Thank you.
