### ISSUE TITLE
Would be good to get MS Teams access 

### ISSUE THREAD

**Issue by shambhu112** [Azure/Microsoft365R#4]
Are there any plans for adding MS Teams access in this package.  Use Cases are
1. Post to Teams with RMD report on a run
2.  Post Images and Graphs to specific teams channels

**Comment by hongooi73** [comment]
This will probably happen after the initial CRAN release. I want to get Sharepoint and authentication working properly first.

**Comment by hongooi73** [comment]
This should now be fully functional, with a CRAN release to happen shortly.

**Comment by hongooi73** [comment]
2.0 is now on CRAN
