### ISSUE TITLE
Accessing Shared OneDrive files

### ISSUE THREAD

**Issue by domsle** [Azure/Microsoft365R#45]
Is it possible to access files that have been shared with me? 
When I am listing files with `odb$list_items()`, I only see files in my own OneDrive directory. Is there any way to access other peoples' shared files?

**Comment by hongooi73** [comment]
There's no built-in method for this right now, but you can get the list by calling the REST API directly:

```r
sh <- odb$do_operation("sharedWithMe", options=list(allowexternal="true"))
objs <- lapply(sh$value, function(obj) ms_drive_item$new(odb$token, odb$tenant, obj$remoteItem))
```

This will work for the first 200 shared items. I'll look into getting a proper implementation into the next version.

**Comment by domsle** [comment]
Thank you for the reply. It works perfectly. 

In this case, I am waiting for the feature to be added in next version :)
