### ISSUE TITLE
Question: downloading item from a SharePoint List

### ISSUE THREAD

**Issue by leungi** [Azure/Microsoft365R#49]
I was unable to find guidance on the subject in package manual, vignette and external forums, so posting it here 😅

I get as far as getting a data frame of items in the list, but I don't see any method to download the items.

Am I missing something, or is this functionality not available yet?

#### Download Attempt with `download.file()`
```r
> sp <- sharepoint_site(
   site_url = config::get("sp_site"),
  app = AzureGraph:::.az_cli_app_id
  )
> 
> sp_path <- sp$get_list("my_list")
> 
> sp_items <- sp_path$list_items()
>
> sp_path$get_item(12391)
<Sharepoint list item ''>
  directory id: 12391 
  web link: https://######.pdf
---
  Methods:
    delete, do_operation, sync_fields, update
>
> my_item <- sp_path$get_item(12391)$do_operation("webURL")$value
>
> download.file(my_item, destfile = "test.pdf")
trying URL 'https://######.pdf'
Error in download.file(my_item, destfile = "test.pdf") : 
  cannot open URL 'https://######.pdf'
In addition: Warning message:
In download.file(my_item, destfile = "test.pdf") :
  cannot open URL 'https://######.pdf': HTTP status was '403 FORBIDDEN'
```

**Comment by hongooi73** [comment]
Look in the `properties` field of the item for all the properties, including `webURL`. You can open this in your browser with `browseURL`; it doesn't contain the contents of the file.

Right now, the properties doesn't actually include fields of the item; I'll fix this. However, note that the data frame does contain the fields, so `sp_items[x, ]` contains all the data for item x.

**Comment by leungi** [comment]
Thanks for the feedback.

Indeed, the value returned in the `webURL` slot of the item is accessible via a browser, but not downloadable apparently.

This comment of yours is key -  _it doesn't contain the contents of the file_.

Is this a limitation of the SharePoint API or a feature waiting to be built 😀

**Comment by hongooi73** [comment]
Actually, it turns out that the data IS included in the properties by default. It's in the `fields` property. I'll clarify this in the docs.

**Comment by leungi** [comment]
Noted.

Here are the key-value under `fields`, and nothing seems to be holding actual _content_.

#### Example (continuing from above)
```r
> item_prop <- sp_path$get_item(12391)$do_operation()
>
> item_prop$fields
$`@odata.etag`
[1] "\"beaf2473-9a34-445b-bbde-e3008a8adb3e,1\""

$FileLeafRef
[1] "xxxx.pdf"

$id
[1] "12391"

$ContentType
[1] "Document"

$Created
[1] "2021-04-29T13:37:07Z"

$AuthorLookupId
[1] "24"

$Modified
[1] "2021-04-29T13:37:07Z"

$EditorLookupId
[1] "24"

$`_CheckinComment`
[1] ""

$LinkFilenameNoMenu
[1] "xxxx.pdf"

$LinkFilename
[1] "xxxx.pdf"

$DocIcon
[1] "pdf"

$FileSizeDisplay
[1] "83338"

$ItemChildCount
[1] "0"

$FolderChildCount
[1] "0"

$`_ComplianceFlags`
[1] ""

$`_ComplianceTag`
[1] ""

$`_ComplianceTagWrittenTime`
[1] ""

$`_ComplianceTagUserId`
[1] ""

$`_CommentCount`
[1] ""

$`_LikeCount`
[1] ""

$`_DisplayName`
[1] ""

$Edit
[1] "0"

$`_UIVersionString`
[1] "1.0"

$ParentVersionStringLookupId
[1] "12391"

$ParentLeafNameLookupId
[1] "12391"
```

**Comment by hongooi73** [comment]
That looks more like a drive item, not a list item. What are you REALLY trying to do?

**Comment by leungi** [comment]
The intent is to download file contents from a SharePoint List.

Normally, users would dump files (e.g., .pdf) into a SharePoint/Teams as items in Documents/Files, and as you noted, the `download_file()` method is applicable.

In this case, files are dumped as items in a List, and there doesn't seem to be a `download_file()` method. As per above, the closest thing is the `webURL`, but using generic `download.file()` doesn't work.

**Comment by hongooi73** [comment]
What do you mean by "dump as items in a list"? How is this done? Via a custom app? What is the column type of the file? Is it an attachment?

**Comment by leungi** [comment]
Apologies for the delay, as I am gathering info to your questions.

The items are dumped into this (presumably) List via Microsoft Flow. The subject List is called _Drilling Well Files_ for reference in reprex below.

When I actually visited the SharePoint site, this _List_ looks like a _Document Library_, and yet it doesn't show up on `list_items()`.

#### R reprex
```r
> sp <- sharepoint_site(
   site_url = "https://xxxx.sharepoint.com/sites/xxxx",
   app = AzureGraph:::.az_cli_app_id
 )
> 
> sp_drive <- sp$get_drive()
> 
> my_items <- sp_drive$list_items(info = "name")
>
> # the document library _Drilling Well Files_ is not detected
> # the document library _General_, which exists by default in SharePoint exist; hence, we're able to `list_files()` on it
> my_items [grepl("(?i)general|drilling", my_items )]
[1] "General"
>
> sp_drive$list_files(
   "General/",
   info = "all"
 ) %>% 
   nrow()
[1] 4
> 
> sp_drive$list_files(
   "Drilling Well Files/",
   info = "all"
 ) %>% 
   nrow()
Error in process_response(res, match.arg(http_status_handler), simplify) : 
  Not Found (HTTP 404). Failed to complete operation. Message:
The resource could not be found.
>
> # signs that _Drilling Well Files_ is a List
> sp$get_list("Drilling Well Files")$list_items() %>% 
   nrow()
[1] 2960
```

#### SharePoint View
![image](https://user-images.githubusercontent.com/30273868/117030885-af07f080-acc5-11eb-8a57-9b98239b4d2c.png)

**Comment by leungi** [comment]
Found the issue; `get_drive()` uses `drive_id` as a parameter, and I used drive name 😅

**Comment by hongooi73** [comment]
lol! Yes, a drive is just a special kind of list as far as Sharepoint is concerned. To get a drive by name, you can call `list_drives()` and select the matching drive.

I'll add a `drive_name` argument to the `get_drive()` method.

**Comment by leungi** [comment]
Thanks for the trouble @hongooi73 🙏

If you're tied on time, I can do a PR; a good excuse for me to learn about R6 classes.
