### ISSUE TITLE
Teams: meeting attendees

### ISSUE THREAD

**Issue by rparrish** [Azure/Microsoft365R#55]
With a specified Teams meeting, I'd like to be able to get the list of attendees. 

Is this currently possible or could it be a feature request?

**Comment by hongooi73** [comment]
This is the same as getting the members of a chat. Will be added at some stage, but requires adding to the permissions of the app registration.

**Comment by hongooi73** [comment]
This is now in the master branch, but also see #69

**Comment by hongooi73** [comment]
Now in 2.3.0
