### ISSUE TITLE
get_sharepoint_site() returns "could not find function make_basic_list" error

### ISSUE THREAD

**Issue by philiporlando** [Azure/Microsoft365R#56]
When running the `get_sharepoint_site()` function with my desired URL (not listed for security reasons), I'm getting the following error:

```
library(Microsoft365R)
site <- get_sharepoint_site("https://some-domain.org/sites/my-team-site")
```

```
Error in make_basic_list(self, "followedSites", filter, n) : 
  could not find function "make_basic_list"
```

**Comment by hongooi73** [comment]
You probably have a `get_sharepoint_site` function in your global environment masking the function in the package. Failing that, try reinstalling Microsoft365R.

Also, the first arg to `get_sharepoint_site` is the site name, not URL.

**Comment by philiporlando** [comment]
Thank you for this info. Explicitly calling `Microsoft365R` and using the `site_name` parameter solved this issue:

```
site <- Microsoft365R::get_sharepoint_site(site_url = "https://some-domain.org/sites/my-team-site")
```

**Comment by hongooi73** [comment]
This is actually a bug, caused by issues in how R6 handles classes that cross package boundaries.

**Comment by hongooi73** [comment]
#58 is the same issue
