### ISSUE TITLE
M365R Authentication

### ISSUE THREAD

**Issue by syanuj108** [Azure/Microsoft365R#57]
Hi. I am attempting to authenticate the M365R package & using the below function. 

get_personal_outlook(tenant="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx")

i get the error - "Error: Not a GUID", however it is a GUID. Any idea why would that happen ? 

Another question - In order to authenticate using my registered app, should the function look like this ? 
get_personal_outlook(tenant="tenantid", app="appid")

Help Appreciated.

**Comment by hongooi73** [comment]
`tenant` is not a valid argument for `get_personal_outlook`; it's a bug that you can specify it. You probably want `get_business_outlook`. To authenticate with your own app, run `get_business_outlook(tenant="tenantid", app="appid")`.

**Comment by syanuj108** [comment]
Thanks. I am still seeing the error - 

Error in process_aad_response(res) : 
  Unauthorized (HTTP 401). Failed to obtain Azure Active Directory token. Message:
AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.

where can i get the documentation for these functions to understand them ? Can you share how would we use this function to be able to authenticate using app registrations ? 

Thanks.

**Comment by hongooi73** [comment]
Your app should have a native client (mobile & desktop) redirect, not a web redirect.

In general, configuring app registrations is something that should be done by your tenant admin. See the AAD documentation for more information. https://docs.microsoft.com/en-au/azure/active-directory/develop/v2-oauth2-auth-code-flow
