### ISSUE TITLE
Access token refreshing

### ISSUE THREAD

**Issue by oestergaardn** [Azure/Microsoft365R#63]
Hi,

This is probably an Admin thing on our side, but I have an issue with refreshing the token. I get the following error:

_Bad Request (HTTP 400). Failed to obtain Azure Active Directory token. Message:
The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on XXXXXXXXXX and the maximum allowed lifetime for this request is 36000._

I'm running on RStudio Server. Everything works, so it's 'just' a matter of extended the 10 hour lifetime. I'm basically looking for some documentation to send to my Admins on this.

Thanks for this package - it is amazing!

**Comment by hongooi73** [comment]
Hi, this looks like something that your admin has changed for your tenant. The normal lifetime for a refresh token is [much longer than that.](https://docs.microsoft.com/en-us/azure/active-directory/develop/refresh-tokens)

Are you having problems logging in after the refresh token is rejected? If so, restart R and run the following:

```r
AzureAuth::clean_token_directory()
AzureGraph::delete_graph_login("yourtenant")
```

**Comment by hongooi73** [comment]
Closing as this is unrelated to Microsoft365R. It may be possible to massage the arguments to `AzureAuth::get_azure_token` (which is what Microsoft365R uses under the hood) to get a custom token lifetime, but this is unlikely to work if you're not an admin.

**Comment by oestergaardn** [comment]
Hi,

Reopen this as I got this answer from my system admin about the refresh token.

_"It does not matter if the refresh token lifetime is 10 years or 5 min, that app itself has to handle this senario correctly, and obviously it does not do that right now. The supposed flow it has to use is to invoke an interactive logon session again if the refresh token has expired, not just assuming it is valid forever."_

Not sure it is something you can fix, but just want to understand whether I have to accept that we cannot use this great package.

**Comment by hongooi73** [comment]
Microsoft365R is doing exactly what is expected of it: check if the token is still valid; refresh it if it's not; throw an error if the refresh fails. When your admin says "that app itself has to handle this scenario correctly", they are referring to **your** app (whether they know it or not). For the purposes of this discussion, an R script counts as an app.

What you should do if the token lifetime is shorter than your expected idle time:

- at the top of the script, try to refresh the token with `token$refresh()`
- if the refresh fails, obtain a new token with `token <- AzureAuth::get_azure_token(*)`
- pass the token to the Microsoft365R client functions

That said, this shows up that the process of handling failed logins needs some massaging. I'll see what I can do.

**Comment by oestergaardn** [comment]
Thank you for the reply @hongooi73.
It's probably just my lack of understanding then (apologies). I managed to login using AzureAuth::get_azure_token(), however can you provide an example / guidance on how to pass that login token to the client functions? My main focus is using the download_file for OneDrive Business. 

OneDrive$download_file(xxx)

Again, thanks for your support on this.

**Comment by hongooi73** [comment]
It's basically just:

```r
token <- AzureAuth::get_azure_token(...)
OneDrive <- get_business_onedrive(token=token)
```

Under the hood, all the MS365R client functions pass their arguments including `...` to `AzureGraph::get_azure_login` and `AzureGraph::create_azure_login`. One of the possible arguments is `token`, which is a token object. The process will be better documented in a coming PR.

If you run into errors, you can try this instead:

```r
token <- AzureAuth::get_azure_token(...)
gr <- AzureGraph::ms_graph$new(token=token)
OneDrive <- gr$get_user()$get_drive()
```

**Comment by oestergaardn** [comment]
Thanks for that.

Unfortunately I still get the same error.

"The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2021-09-14T07:06:44.24XXXXX and the maximum allowed lifetime for this request is 36000."

Seems like we have to give up on this, but appreciate the support from you on this.

**Comment by hongooi73** [comment]
As noted previously, you can also run `AzureAuth::clean_token_directory` to delete cached tokens. Try adding this to the top of your script.
