### ISSUE TITLE
Shared mailboxes in business outlook

### ISSUE THREAD

**Issue by isaac-florence** [Azure/Microsoft365R#64]
Please could functionality be added to allow emails to be sent and read from shared mailboxes that the user login has access to?

Thank you for creating this excellent package, it's been a real gamechanger for our workflows in terms of alerts, distribution, and monitoring!

**Comment by hongooi73** [comment]
Thanks, but this is a duplicate of #39 😊

**Comment by isaac-florence** [comment]
Aha! My apologies. Thank you for your swift reply!
