### ISSUE TITLE
How to register microsoft365R so that all users can access it

### ISSUE THREAD

**Issue by SamadCWI** [Azure/Microsoft365R#66]

**Comment by hongooi73** [comment]
Can you be more specific?

**Comment by SamadCWI** [comment]
Hello Hong,

How we can use this feature? When a normal user installed the package and try to run it, it gives a prompt for admin approval and being as a admin approval I am not able to find this application in azure or O365 to give access.

We are new to use this feature and I would appreciate if you can help us to register it

Regards,
AbdulSamad

From: Hong Ooi ***@***.***>
Sent: 07 July 2021 20:19
To: Azure/Microsoft365R ***@***.***>
Cc: Abdul Samad (Consultant) ***@***.***>; Author ***@***.***>
Subject: (Suspected Marketing Email)Re: [Azure/Microsoft365R] How to register microsoft365R so that all users can access it (#66)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender , otherwise report this email as phishing


Can you be more specific?

-

**Comment by hongooi73** [comment]
I'm not an admin so I've never had to do this myself, but does this help?

https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/grant-admin-consent

**Comment by SamadCWI** [comment]
Yes, I checked it but the Microsoft365R is not showing under app registration so won't be able to provide the permission. For that we have to register it first.

Regards,

From: Hong Ooi ***@***.***>
Sent: 08 July 2021 23:37
To: Azure/Microsoft365R ***@***.***>
Cc: Abdul Samad (Consultant) ***@***.***>; Author ***@***.***>
Subject: (Suspected Marketing Email)Re: [Azure/Microsoft365R] How to register microsoft365R so that all users can access it (#66)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender , otherwise report this email as phishing


I'm not an admin so I've never had to do this myself, but does this help?

https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/grant-admin-consent<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Factive-directory%2Fmanage-apps%2Fgrant-admin-consent&data=04%7C01%7CASamad%40isdb.org%7Ca7f6938e45c94352f28b08d9423b274c%7C8fa69c26409d43e5973c17a8be1a7f35%7C0%7C0%7C637613644093747505%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=48e40vU4Vsk4ELlDEzZZ46DBV5asAK9N80XY05irdaQ%3D&reserved=0>

-

**Comment by hongooi73** [comment]
External apps don't show up under app registrations. You should find this under "Enterprise Apps", or you can try this URL:
```
https://login.microsoftonline.com/yourtenantid/adminconsent?client_id=d44a05d5-c6a5-4bbb-82d2-443123722380
```
Note that I'm not an AAD expert. You should really contact MS tech support if you need help navigating the Azure portal, or ask on a forum.

**Comment by SamadCWI** [comment]
I had a discussion with Microsoft and they asked me to open a ticket with GITHUB.

Regards,
AbdulSamad

From: Hong Ooi ***@***.***>
Sent: 11 July 2021 21:29
To: Azure/Microsoft365R ***@***.***>
Cc: Abdul Samad (Consultant) ***@***.***>; Author ***@***.***>
Subject: (Suspected Marketing Email)Re: [Azure/Microsoft365R] How to register microsoft365R so that all users can access it (#66)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender , otherwise report this email as phishing


External apps don't show up under app registrations. You should find this under "Enterprise Apps", or you can try this URL:

https://login.microsoftonline.com/yourtenantid/adminconsent?client_id=d44a05d5-c6a5-4bbb-82d2-443123722380

Note that I'm not an AAD expert. You should really contact MS tech support if you need help navigating the Azure portal, or ask on a forum.

-
