### ISSUE TITLE
can't connect to my OneDrive account at my workplace

### ISSUE THREAD

**Issue by pcantalupo** [Azure/Microsoft365R#67]
Hello,  I don't have a personal OneDrive account but rather use OneDrive at the University that I work for.  I get access to Microsoft 365 through my University by using their Single Sign on.  Is there a way to use this repo to connect to my workplace OneDrive account?

**Comment by hongooi73** [comment]
You can try `get_business_onedrive`. It's for any organizational account, not just businesses.

**Comment by hongooi73** [comment]
I'm closing this for now; reply here if you're still having problems.
