### ISSUE TITLE
Download file in specific folder

### ISSUE THREAD

**Issue by EtienneClaverie** [Azure/Microsoft365R#76]
Hi,
Thanks for this excellent package that enhance my collaboration with my colleagues!
I would like to know how could I precise to donwload the file into a specific folder, somehting like
drv$download_file("General/xxxx/xxx/xxxx.csv",
                  overwrite = TRUE,
                  dest="data/") so that my file will be download in my local data/ folder.

Thnaks,
Etienne

**Comment by hongooi73** [comment]
You need to append the name of the file, like so:

```
drv$download_file("General/xxxx/xxx/xxxx.csv", dest="data/xxxx.csv")
```

**Comment by EtienneClaverie** [comment]
Thanks !
