### ISSUE TITLE
access the user list to look up the ids

### ISSUE THREAD

**Issue by ycphs** [Azure/Microsoft365R#77]
for every site a list with the useres is provided.

"domain.sharepoint.com/sites/{site}/_catalogs/users/detail.aspx"

in SO the issue is solved with the graph API:

[get lookup id](https://stackoverflow.com/questions/64867311/get-sharepoint-user-by-lookup-id-using-microsoft-graph)

`list_items()` 
returns always the information about the author and the editor as AuthorLookupId and EditorLookupId.

It would be great if it is possible to use get the information.

**Comment by hongooi73** [comment]
You can get the user list by adding a `filter` argument, as shown in the SO answer:

```r
site$get_lists(filter="DisplayName eq 'User Information List'")
```

Or if you want the user list itself (rather than as the component of a list of 1):

```r
site$get_list("User Information List")
```

**Comment by ycphs** [comment]
Thank you!
