### ISSUE TITLE
Error when specifying app id

### ISSUE THREAD

**Issue by eveyp** [Azure/Microsoft365R#78]
When using the authentication workaround to include `app = "04b07795-8ddb-461a-bbee-02f9e1bf7b46"`, I'm getting an error: 
`Error in as.vector(x, "character") : 
  cannot coerce type 'environment' to vector of type 'character'`

This isn't happening when I leave off the `app` argument.

For example:
`get_team("Team Name")`
doesn't throw an error.

`get_team("Team Name",  app = "04b07795-8ddb-461a-bbee-02f9e1bf7b46")`
leads to the error:
`Error in as.vector(x, "character") : 
  cannot coerce type 'environment' to vector of type 'character'`

**Comment by hongooi73** [comment]
I can't reproduce this error. Post the full error message, your `sessionInfo()` and what `traceback()` shows.

**Comment by hongooi73** [comment]
Also, if `get_team` works without specifying an app, that means your org has approved the Microsoft365R app id for use, so you shouldn't need a workaround
