### ISSUE TITLE
Which admin rights are needed for list_chats() and list_teams()?

### ISSUE THREAD

**Issue by gfspiteri** [Azure/Microsoft365R#81]
Hi, trying the list_chats() and list_teams() functions however get a "Need admin approval" message in the browser. Are there some specific rights I need to ask the admin team for? My aim is to try to send messages from R code which takes quite long to chats in MS teams. Many thanks!

**Comment by hongooi73** [comment]
The full list of required permissions is in [inst/app_registration.md](../blob/master/inst/app_registration.md).

**Comment by gfspiteri** [comment]
Many thanks and apologies, I don't know how I missed the very prominent paragraph on authentication.
