### ISSUE TITLE
Pass an item path to the read functions of other packages

### ISSUE THREAD

**Issue by adam-gruer** [Azure/Microsoft365R#9]
Hong, such a great package.  I could cry.  Feel closer than I ever have at being able to interact with Office365 and SharePoint from R.
Amazing work.

Is there a way  to pass a path of an item such that a function like readxl::read_xlsx could read the spreadsheet into R?
I'd rather avoid downloading the file if I can .
e.g.
```r
site <- sharepoint_site(url)
drv <- site$get_drive()
item<- drv$get_item("Cool_data.xlsx")

##??
data <- readxl::read_xlsx(item${some_method} )
```

**Comment by hongooi73** [comment]
Thanks!

In the specific case of `read_xlsx`, you have to download the file because it requires a filename. Even passing a URL or connection doesn't work. However, you can do something like this:

```r
read_xlsx_from_onedrive <- function(drv, path)
{
  tmpfile <- tempfile(fileext=".xlsx")
  on.exit(unlink(tmpfile)
  drv$download_file(path, tmpfile)
  readxl::read_xlsx(tmpfile)
}
```

**Comment by adam-gruer** [comment]
Thanks @hongooi73  that makes sense - I went for the wrong tool for what I am trying to do.

I read some of your source code and Microsoft's Graph Rest API docs and it is starting to click what I'm trying to do.
Which is build a request with the item's `do_operation` method that matches the specification in the API docs

e.g.
```r
site <- sharepoint_site(url)
drv <- site$get_drive()
item<- drv$get_item("Cool_data.xlsx")

rng <- item$do_operation(file.path("workbook", "worksheets","Sheet1","usedRange")
# TODO parse returned list and values JSON elemnt into a data.frame/tibble
```
My current understanding of what to supply as arguments to `do_operation` is very rudimentary apart from understanding that I can build the path I need as specified in the API docs and supply an http verb if I need to, I'm keen to learn some more about that.

 I'm writing a vignette documenting this particular workflow. 
 
Would you be open to me submitting the vignette as a pull request? 

 Perhaps I could eventually  develop it into some new methods or an extension package/object specifically for excel workbooks on Sharepoint.

**Comment by hongooi73** [comment]
A vignette would be great! I've already submitted this to CRAN, but it can go in the next release. I've got Teams access already planned.

**Comment by mfherman** [comment]
@adam-gruer have you made any progress on this? I'm thinking I may want to implement a similar workflow.

**Comment by mrworthington** [comment]
Reviving this where @mfherman left off. Would love to know of a way where I can read an excel file directly through {Microsoft365R} without having to download the excel file locally. I ended up at `do_operation()` but am stuck at this point.
