### ISSUE TITLE
Opening File on Sharepoint in R as dataframe

### ISSUE THREAD

**Issue by aylin-m** [Azure/Microsoft365R#96]
Hi all, 

I have been able to successfully follow the drv<-site$get_drive() instructions. I can see the items listed in the directory set from the site. 

I have tried open_item and see that the file only opens in the browser. Is there currently capacity within Microsoft365R to open a file from Sharepoint into R without downloading the file? Ideally the file would be opened as a dataframe. 

Thanks for your help.

**Comment by hongooi73** [comment]
Any method to do this would involve downloading the file anyway, so there isn't much benefit to adding it to the package.

If you want to avoid files cluttering up your project, download to the temp directory:

```r
f <- tempfile()
drv$download_file("path/to/file", f)

df <- read.csv(f)  # or whatever function you use to read the file
```

**Comment by hongooi73** [comment]
There are now convenience methods to do this for csv/tsv files: `save_dataframe` and `load_dataframe`. See `?ms_drive` and `?ms_drive_item` for more info.
